- hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: mongo
  gather_facts: yes
  become: true
  roles:
  - mongodb

- hosts: redis
  gather_facts: yes
  become: true
  roles:
  - redis

- hosts: tyk_dashboard
  gather_facts: yes
  become: true
  roles:
  - tyk_dashboard
  - tyk_dashboard_users

- hosts: tyk_pump
  gather_facts: yes
  become: true
  roles:
  - tyk_pump

- hosts: tyk_gateway_with_dashboard
  gather_facts: yes
  become: true
  roles:
  - tyk_gateway_with_dashboard

- hosts: tyk_gateway_with_dashboard
  gather_facts: yes
  become: true
  roles:
  - tyk_python
  - tyk_plugin
