#####  Install python3.4

- name: Install python 3.4 dependancies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - checkinstall
    - libreadline-gplv2-dev
    - libncursesw5-dev
    - libssl-dev
    - libsqlite3-dev
    - tk-dev
    - libgdbm-dev
    - libc6-dev
    - libbz2-dev

- name: Check if python3.4 is installed
  stat:
    path: /usr/local/bin/python3.4
  register: python34_installed

- block:
  - name: Fetch the python 3.4.7 dist
    get_url:
      url:  https://www.python.org/ftp/python/3.4.7/Python-3.4.7.tgz
      dest: /usr/src/Python-3.4.7.tgz

  - name: Untar the file
    shell: tar -xvzf Python-3.4.7.tgz
    args:
      chdir: /usr/src

  - name: Configure python
    shell: ./configure --enable-shared --libdir=/usr/local/lib LDFLAGS="-Wl,--rpath=/usr/local/lib"
    args:
      chdir: /usr/src/Python-3.4.7

  - name: Make install Python-3.4.7
    make:
      chdir: /usr/src/Python-3.4.7
      target: altinstall

  when: not python34_installed.stat.exists

- name: Link the python libs so tyk can find them
  file:
    src: /usr/local/lib/{{item}}
    dest: /usr/lib/x86_64-linux-gnu/{{ item }}
    state: link
  with_items:
  - libpython3.4m.so
  - libpython3.4m.so.1.0

- name: Install protobuf
  pip:
    name: protobuf
    executable: pip3.4

- name: Install HTTP/2-based RPC framework
  pip:
    name: grpcio
    executable: pip3.4

- name: Give the tyk-gateway-lua service a unique name
  lineinfile:
    name: /etc/init.d/tyk-gateway-lua
    regexp: '^# Provides:\s+tyk-gateway$'
    backrefs: yes
    line: '# Provides:          tyk-gateway-lua'

- name: Give the tyk-gateway-python service a unique name
  lineinfile:
    name: /etc/init.d/tyk-gateway-python
    regexp: '^# Provides:\s+tyk-gateway$'
    backrefs: yes
    line: '# Provides:          tyk-gateway-python'

### Switch from tyk-gateway to tyk-gateway-python

- name: Stop tyk-gateway
  service:
    name: tyk-gateway
    state: stopped
    enabled: no

- name: Start tyk-gateway-python
  service:
    name: tyk-gateway-python
    state: started
    enabled: yes
